services:
  product-service:
    image: product-service:latest
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8070
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=productdb
      - TZ=Asia/Kolkata
      - LOG_FILE=/var/log/app/product-service.log
      - JAVA_OPTS=-Dlogback.configurationFile=/logs/logback-spring.xml
    volumes:
      - ../logs:/var/log/app
      - ./src/main/resources/logback-spring.xml:/logs/logback-spring.xml
    networks:
      - common
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: product_service

networks:
  common:
    external: true
