input {
  file {
    path => "/logs/*"  # This should match the mounted volume path
    start_position => "beginning"
    sincedb_path => "NUL"  # Disables sincedb for simplicity
  }
}

output {
  stdout {
    codec => rubydebug
  }
}